# -*- coding: utf-8 -*-
"""Data_Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10FmH_ht9ux7YLsxZMrxONWqkdkATa4XZ
"""

# import sys
# sys.path.append('/content/')

import codecs
import pandas as pd
import re
import string
import preprocessing_functions as prec

# !gdown --id 1GAJJWPMtapTN_Cxhdo2kL8VZa7PIQp7x

raw_data = pd.read_json(codecs.open('df.json', 'r', 'utf-8'))

df = raw_data.copy()

df['text'] = df['text'].apply(prec.preprocess)

"""## Save data and copy to drive"""

with open('df_clean.json', 'w', encoding='utf-8') as file:
    df.to_json(file, force_ascii=False)

# from google.colab import drive
# drive.mount('/content/drive')

# !cp df_clean.json /content/drive/MyDrive